### ISSUE TITLE
In Eclipse, activate the "insert spaces for tabs" option by default

### ISSUE THREAD

**Issue by jbaltus** [CIRB/devbox#38]
Hi, 

lint is very sensitive and when users uses the tab key, a tab is inserted -> error in lint. 
Could you enable the "insert spaces for tabs" + "Show whitespace characters" options in Eclipse by default  ? 

Thanks in advance !

**Comment by pradermecker** [comment]
This is done is 3.2 which will be release in a couple of weeks.
The eclipse pref file is https://github.com/CIRB/devbox-dotfiles/blob/master/.eclipse/workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.editors.prefs
It is only activate if you use ".eclipse/workspace" as your workspace location.

I haven't add `"Show whitespace characters` (just yet) because I believe it is a personal preference.

To persist your personal preferences in the devbox, please follow [these intructions](https://github.com/CIRB/devbox#personal-mr-repositories)
